import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "./components/ui/NavBar";
import Footer from "./components/ui/Footer";
import { LanguageProvider } from "@/contexts/LanguageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ background: "black", color: "#fff", fontFamily: "sans-serif" }}
      >
        <LanguageProvider>
          <MenuBar />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
