import type { Metadata } from 'next';
import './globals.css';
import { LanguageProvider } from '@/contexts/LanguageContext';
import Footer from './components/ui/Footer';
import MenuBar from './components/ui/NavBar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				style={{ background: 'black', color: '#fff', fontFamily: 'sans-serif' }}
			>
				<LanguageProvider>
					<MenuBar />
					{children}
					<Footer />
				</LanguageProvider>
			</body>
		</html>
	);
}
